name: Maven Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install OpenJFX
      run: |
        sudo apt-get update -qy
        sudo apt-get install -y openjfx

    - name: Build with Maven
      run: |
    
        mvn compile
        mvn clean install
       
